import React, { useEffect, useRef } from 'react';
import { setupCanvas, observeCanvas } from '../lib/canvasKit';
import type { WidgetProps } from './registry';

export const COLORS={bg:'#f5f8f0',light:'#b8c9a7',dark:'#76906a',route:'#92400e',blue:'#27446e',green:'#228d5c',red:'#c43f52',orange:'#f07e47',purple:'#7c3aed',ink:'#21324a',muted:'#68778f',border:'#d7deea'};
export function clearTrailScene(ctx:CanvasRenderingContext2D,w:number,h:number){ctx.fillStyle=COLORS.bg;ctx.fillRect(0,0,w,h);ctx.fillStyle=COLORS.light;ctx.beginPath();ctx.moveTo(0,h*.74);ctx.quadraticCurveTo(w*.25,h*.6,w*.5,h*.73);ctx.quadraticCurveTo(w*.78,h*.84,w,h*.66);ctx.lineTo(w,h);ctx.lineTo(0,h);ctx.fill();}
export function drawTrail(ctx:CanvasRenderingContext2D,w:number,h:number,color=COLORS.route,broken=false){ctx.lineCap='round';ctx.lineWidth=16;ctx.strokeStyle='#dce7d5';ctx.beginPath();ctx.moveTo(30,h*.72);ctx.quadraticCurveTo(w*.34,h*.58,w*.68,h*.69);ctx.quadraticCurveTo(w*.82,h*.74,w-34,h*.36);ctx.stroke();ctx.lineWidth=4;ctx.strokeStyle=color;if(broken)ctx.setLineDash([8,8]);ctx.beginPath();ctx.moveTo(30,h*.72);ctx.quadraticCurveTo(w*.34,h*.58,w*.68,h*.69);ctx.quadraticCurveTo(w*.82,h*.74,w-34,h*.36);ctx.stroke();ctx.setLineDash([]);}
export function drawHiker(ctx:CanvasRenderingContext2D,x:number,y:number,color=COLORS.blue,scale=1){ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y-15*scale,7*scale,0,Math.PI*2);ctx.fill();ctx.lineWidth=3;ctx.strokeStyle=color;ctx.beginPath();ctx.moveTo(x,y-8*scale);ctx.lineTo(x-5*scale,y+10*scale);ctx.lineTo(x-12*scale,y+18*scale);ctx.moveTo(x,y-8*scale);ctx.lineTo(x+8*scale,y+9*scale);ctx.lineTo(x+15*scale,y+15*scale);ctx.stroke();ctx.fillStyle=COLORS.orange;ctx.fillRect(x+7*scale,y-7*scale,10*scale,13*scale);}
export function drawMarker(ctx:CanvasRenderingContext2D,x:number,y:number,color=COLORS.green){ctx.strokeStyle=COLORS.route;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x,y-34);ctx.stroke();ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(x,y-34);ctx.lineTo(x+28,y-27);ctx.lineTo(x,y-20);ctx.closePath();ctx.fill();}
export function drawNotebook(ctx:CanvasRenderingContext2D,x:number,y:number,w=110,h=70,accent=COLORS.blue){ctx.fillStyle='#fff';ctx.strokeStyle=COLORS.border;ctx.lineWidth=2;ctx.fillRect(x,y,w,h);ctx.strokeRect(x,y,w,h);ctx.strokeStyle=accent;ctx.lineWidth=3;for(let i=0;i<3;i++){ctx.beginPath();ctx.moveTo(x+16,y+20+i*16);ctx.lineTo(x+w-14,y+20+i*16);ctx.stroke();}}
export function drawMap(ctx:CanvasRenderingContext2D,x:number,y:number,w=130,h=76,accent=COLORS.blue){ctx.fillStyle='#fff';ctx.strokeStyle=COLORS.border;ctx.lineWidth=2;ctx.fillRect(x,y,w,h);ctx.strokeRect(x,y,w,h);ctx.strokeStyle=accent;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x+12,y+h-14);ctx.quadraticCurveTo(x+w*.35,y+12,x+w-16,y+20);ctx.stroke();ctx.fillStyle=COLORS.green;ctx.beginPath();ctx.arc(x+w-24,y+20,5,0,Math.PI*2);ctx.fill();}
export function drawTechnicalInset(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,title:string,value:number,color=COLORS.blue){ctx.fillStyle='#fff';ctx.strokeStyle=COLORS.border;ctx.lineWidth=2;ctx.fillRect(x,y,w,h);ctx.strokeRect(x,y,w,h);ctx.fillStyle=COLORS.ink;ctx.font='16px Segoe UI,sans-serif';ctx.fillText(title,x+14,y+24);ctx.fillStyle=color;ctx.fillRect(x+16,y+h-28,(w-32)*Math.max(0,Math.min(1,value)),10);ctx.fillStyle=COLORS.ink;ctx.font='22px Segoe UI,sans-serif';ctx.fillText(value.toFixed(2),x+w-62,y+h-35);}

export const HikeAnalogy:React.FC<WidgetProps>=({chapterId})=>{const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const c=ref.current;if(!c)return;const ctx=setupCanvas(c,560,140);let raf:number|null=null;let alive=true;const reduced=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;const start=performance.now();const tick=(now:number)=>{const t=reduced?.55:((now-start)%3000)/3000;clearTrailScene(ctx,560,140);drawTrail(ctx,560,140,chapterId==='chap-1'?COLORS.red:COLORS.route,chapterId==='chap-1');let px=50+t*430,py=100-t*44;if(chapterId==='chap-3'){px=490-t*420;py=75+t*22;}if(chapterId==='chap-2'){drawMap(ctx,350,42);px=240;py=96;}if(chapterId==='chap-7'){drawNotebook(ctx,360,48,110,70,COLORS.orange);px=250;py=98;}if(chapterId==='chap-8')drawNotebook(ctx,360,48,110,70,COLORS.purple);if(chapterId==='chap-10')drawNotebook(ctx,360,48,110,70,COLORS.green);drawHiker(ctx,px,py,chapterId==='chap-1'?COLORS.red:COLORS.blue,1.1);drawMarker(ctx,505,78,chapterId==='chap-1'?COLORS.red:COLORS.green);if(!c.classList.contains('is-ready'))c.classList.add('is-ready');if(alive)raf=requestAnimationFrame(tick);};const stop=()=>{alive=false;if(raf){cancelAnimationFrame(raf);raf=null;}};const startLoop=()=>{alive=true;if(!raf)raf=requestAnimationFrame(tick);};const disconnect=observeCanvas(c,startLoop,stop);startLoop();return()=>{stop();disconnect();};},[chapterId]);return <canvas ref={ref} width={560} height={140} aria-label='徒步动作示意'/>;};
export default HikeAnalogy;
