import React, { useState } from 'react';
import { datasets, methods } from '../data/knowledge';
import { table1Absolute, table1ImageNetCub, type Table1MethodId, type Table1Row } from '../data/tableResults';
import { useReferenceHub } from '../components/ReferencePrimitives';

type ClaimId = 'reduces'|'plasticity'|'joint'|'domain'|'response'|'loss'|'warmup'|'sequence';
type EvidenceKind = 'Measured Result'|'Author Interpretation'|'Our Mechanism Explanation'|'General ML Background'|'Teaching Toy'|'Implementation Note';
const claimItems: {id:ClaimId;title:string;verdict:'Supported'|'Too strong'|'Not directly tested';evidence:string[];related:string[];setup:string;result:string;interpretation:string;boundary:string;kind:EvidenceKind}[] = [
  {id:'reduces',title:'在论文报告的多数任务对中，LwF 比 fine-tuning 减少旧任务退化',verdict:'Supported',evidence:['Table 1','Figure 4','C06'],related:['A','H'],setup:'单次新任务分类比较与逐步加入任务的序列；任务对、模型、split 与 metric 需分别阅读。',result:'论文在多个被测设置中报告 LwF 相比 fine-tuning 的 old-task trade-off 较好。',interpretation:'旧响应提供了新数据上的额外旧任务约束。',boundary:'不是消除遗忘的保证；存在任务对与架构例外。',kind:'Measured Result'},
  {id:'plasticity',title:'LwF 比 feature extraction 保留更多新任务适配能力',verdict:'Supported',evidence:['Table 1','C06'],related:['A','E'],setup:'Feature Extraction 冻结共享参数；LwF 联合阶段更新共享参数并约束旧响应。',result:'表中多个设置显示 Feature Extraction 的旧任务保持较强但新任务学习较弱。',interpretation:'LwF 在稳定与可塑之间作折衷。',boundary:'不是所有任务对都保证同一排序；梯度尺度和任务关系会影响结果。',kind:'Measured Result'},
  {id:'joint',title:'LwF 在若干 AlexNet 任务对中接近 Joint Training',verdict:'Supported',evidence:['Table 1','C06'],related:['A','E'],setup:'Table 1 的部分 AlexNet task pair；Joint Training 可访问旧训练数据与标签，LwF 不可。',result:'若干任务对总体表现相近，训练信息条件不同。',interpretation:'旧模型响应在不保留旧图像时提供间接约束。',boundary:'不能扩大成所有任务、所有架构等价；VGG 实验不支持普遍等价说法。',kind:'Measured Result'},
  {id:'domain',title:'Task mismatch 可能削弱新输入上旧响应约束的覆盖',verdict:'Supported',evidence:['Table 1','C07','E05'],related:['G'],setup:'论文比较多种任务对，并在讨论中解释 CUB / MNIST 等不相似案例。',result:'论文报告表现随 task pair 改变；E05 只登记定性边界，不构成 pooled domain score。',interpretation:'Mechanism：当 Xₙ 未覆盖旧任务相关区域时，响应损失对该区域没有直接监督。',boundary:'这是作者解释与本教程机制解释，不是仅凭结果确定的单因果结论。',kind:'Author Interpretation'},
  {id:'response',title:'响应正则优于论文测试的 parameter-L2 baseline',verdict:'Supported',evidence:['Figure 7(a)(b)','C11'],related:['F'],setup:'Figure 7 比较响应正则与共享参数软约束 baseline 的 old/new performance。',result:'所测设置中 output / response regularization 优于该 parameter-L2 对照。',interpretation:'输出行为与参数坐标距离不是同一个约束对象。',boundary:'结论只覆盖论文所测任务对和 baseline，不是所有参数正则的普遍比较。',kind:'Measured Result'},
  {id:'loss',title:'某一种 response loss 是 LwF 唯一有效选择',verdict:'Too strong',evidence:['Figure 7(c)(d)','C08'],related:['D'],setup:'KD、cross-entropy、L1 与 L2 response-loss variants 对照。',result:'KD 略优，但报告差异不大。',interpretation:'证据更支持“保持旧输出”的设计方向，而不是 KD 这个损失名称不可替代。',boundary:'不证明所有 response loss 完全等价；“唯一必要”也不是该 ablation 直接测试的结论。',kind:'Measured Result'},
  {id:'warmup',title:'Warm-up 对 LwF 在所报告消融中并非关键',verdict:'Supported',evidence:['Table 2(b)','C05'],related:['B','C'],setup:'ImageNet→CUB 的 warm-up / no-warm-up 对照；同时包含 fine-tuning 对照。',result:'作者报告 warm-up 对 LwF 不关键，但对 fine-tuning 的旧任务保持更重要。',interpretation:'warm-up 帮助新 head 起步，但不构成 LwF 定义的核心约束。',boundary:'只对报告消融成立，不推广到所有训练方案。',kind:'Measured Result'},
  {id:'sequence',title:'连续加入任务后旧任务仍可能退化',verdict:'Supported',evidence:['Figure 4','E05'],related:['H'],setup:'Places365→VOC parts；ImageNet→Indoor Scenes parts；逐阶段任务评估。',result:'Figure 4 显示序列阶段中的旧任务表现变化，LwF 通常比 fine-tuning 退化更慢，但多阶段后仍可能落后于 Joint Training。',interpretation:'每阶段前一 Student 成为下一 Teacher，局部 response matching 并非永久锚定 Model₀。',boundary:'不说明每一任务每一步必然下降，也不支持线性误差累积定律。',kind:'Measured Result'},
];
const evidenceKinds: EvidenceKind[] = ['Measured Result','Author Interpretation','Our Mechanism Explanation','General ML Background','Teaching Toy','Implementation Note'];
const judgmentOptions = [
  {text:'LwF eliminates catastrophic forgetting.',verdict:'Too strong',evidence:'Table 1 · Figure 4',boundary:'多个测试设置仍显示旧任务退化；论文没有 no-forgetting theorem。',related:'Scene F / G / H'},
  {text:'在论文报告的设置中，LwF 常比 fine-tuning 减少旧任务退化。',verdict:'Supported',evidence:'Table 1 · Figure 4 · C06',boundary:'限定到报告任务对、架构、数据切分与 metric。',related:'Scene A / H'},
  {text:'KD loss 是 LwF 必不可少的组成部分。',verdict:'Not directly tested',evidence:'Figure 7(c)(d) compares KD, cross-entropy, L1 and L2.',boundary:'实验比较了不同 response loss；KD 略优但优势不大。',related:'Scene D'},
  {text:'在所有架构中，LwF 与 Joint Training 等价。',verdict:'Too strong',evidence:'Table 1 includes different architecture results.',boundary:'AlexNet 的若干任务对接近；VGG 结果不支持普遍等价。',related:'Scene A'},
  {text:'在 Xₙ 上响应匹配证明 pₒ 上的整个函数不变。',verdict:'Too strong',evidence:'C02 · C07 · Figure 7 discussion.',boundary:'旧响应只在所见的新任务输入上直接受约束。',related:'Scene F / G'},
];
const methodsById = new Map(methods.map((item)=>[item.id,item]));
const datasetById = new Map(datasets.map((item)=>[item.id,item]));

export function SceneI({ onNavigate }: { onNavigate:(scene:'A'|'B'|'C'|'D'|'E'|'F'|'G'|'H'|'J')=>void }) {
  const { openHub } = useReferenceHub();
  const [claimId,setClaimId]=useState<ClaimId>('reduces');
  const [format,setFormat]=useState<'paper'|'absolute'>('paper');
  const [selectedMethod,setSelectedMethod]=useState<Table1MethodId>('lwf');
  const [judgmentIndex,setJudgmentIndex]=useState(0);
  const [evidenceFilter,setEvidenceFilter]=useState<EvidenceKind[]>(evidenceKinds.slice(0,4));
  const [selectedNode,setSelectedNode]=useState('Table 1');
  const claim=claimItems.find((item)=>item.id===claimId)!;
  const judgement=judgmentOptions[judgmentIndex];
  const row=table1ImageNetCub.methods.find((item)=>item.id===selectedMethod)!;
  const absolute=table1Absolute(row);
  const selectedMethodCard=methodsById.get(methodCardId(selectedMethod));

  const toggleEvidenceFilter=(kind:EvidenceKind)=>setEvidenceFilter((current)=>current.includes(kind)?current.filter((item)=>item!==kind):[...current,kind]);

  const openEvidence = (id:string) => openHub({evidenceId:registryEvidenceId(id)});
  return <div className="v2-scene-content v2-scene-i">
    <section className="v2-i-intro v2-state-card"><div className="v2-section-title-row"><div><p className="v2-eyebrow">CLAIM → SETUP → EVIDENCE → INTERPRETATION → BOUNDARY</p><h2>这项实验究竟支持哪一句话？</h2></div><button className="v2-intro-evidence" type="button" onClick={()=>openHub({evidenceId:'C06'})}>证据登记 C06 ↗</button></div><p>本页把论文结果与作者解释、机制说明分层。先检查实验条件，再看数字与原图；没有被实验覆盖的结论会明确标成过强或未直接测试。</p><div className="v2-i-claim-grid">{claimItems.map((item)=><button type="button" key={item.id} className={claimId===item.id?'is-selected':''} onClick={()=>setClaimId(item.id)}><span>{item.kind}</span><strong>{item.title}</strong><b className={`is-${item.verdict.toLowerCase().replace(/ /g,'-')}`}>{item.verdict}</b></button>)}</div><ClaimChain claim={claim} onEvidence={(id)=>{setSelectedNode(id);openEvidence(id);}} onNavigate={onNavigate} /></section>

    <section className="v2-i-table v2-state-card"><div className="v2-section-title-row"><div><p className="v2-eyebrow">TABLE 1 READER · IMAGENET → CUB · ALEXNET</p><h2>论文行格式与重构绝对值分开查看</h2></div><button className="v2-intro-evidence" type="button" onClick={()=>openHub({evidenceId:'E01'})}>来源 E01 ↗</button></div><ExperimentSetup />
      <div className="v2-i-format-toggle" role="group" aria-label="Table 1 数值格式"><button type="button" aria-pressed={format==='paper'} onClick={()=>setFormat('paper')}>Original Paper Format</button><button type="button" aria-pressed={format==='absolute'} onClick={()=>setFormat('absolute')}>Reconstructed Absolute Values</button></div>
      <div className="v2-i-table-wrap"><table className="v2-i-results-table"><thead><tr><th scope="col">Method</th><th scope="col">{format==='paper'?'Old · acc. / Δ pp':'Old · acc. %'}</th><th scope="col">{format==='paper'?'New · acc. / Δ pp':'New · acc. %'}</th></tr></thead><tbody>{table1ImageNetCub.methods.map((method)=>{const values=table1Absolute(method);return <tr key={method.id} className={method.id===selectedMethod?'is-selected':''} onClick={()=>setSelectedMethod(method.id)}><th scope="row"><button type="button" onClick={()=>setSelectedMethod(method.id)}>{method.label}</button></th><td>{format==='paper'&&method.id!=='lwf'?`${signed(method.oldDelta!)} pp`:`${values.old.toFixed(1)}%`}</td><td>{format==='paper'&&method.id!=='lwf'?`${signed(method.newDelta!)} pp`:`${values.next.toFixed(1)}%`}</td></tr>;})}</tbody></table></div>
      <div className="v2-i-delta-note"><strong>{format==='paper'?'论文格式：LwF 显示绝对值，其他方法显示相对 LwF 的带符号差值。':'重构格式：method absolute = LwF absolute + reported signed delta。'}</strong>{format==='absolute'?<span>Fine-tuning / Feature Extraction / Joint Training 的重构值均标记为 reconstructed from paper-reported delta，不是原表直接打印的绝对值。</span>:<span>符号按 old-task / new-task 两列分别相对 LwF 基线。点击一行查看方法的信息条件。</span>}</div>
      <div className="v2-i-result-grid"><PerformancePlot onSelect={setSelectedMethod} selected={selectedMethod} /><MethodConstraint method={row} info={selectedMethodCard?.summary||''} absolute={absolute} /></div>
    </section>

    <section className="v2-i-ablation v2-state-card"><div className="v2-section-title-row"><div><p className="v2-eyebrow">TABLE 2 · ORGANIZED BY RESEARCH QUESTION</p><h2>架构与训练消融揭示了什么？</h2></div><button type="button" className="v2-intro-evidence" onClick={()=>openHub({evidenceId:'A08'})}>Table 2 来源 ↗</button></div><div className="v2-i-ablation-grid">{[
        ['Architecture','output layer / last hidden / 2nd-last hidden','没有观察到增加 task-specific layers 的一致优势；具体设置见原表。','Scene B'],
        ['Network expansion','expansion / expansion + LwF','表现与普通 LwF 相近，但扩展带来额外存储、计算与结构复杂度。','Scene B'],
        ['Warm-up','LwF / no warm-up 与 fine-tuning 对照','warm-up 对 LwF 并非关键；对 fine-tuning 的旧任务保持更重要。','Scene B / C'],
        ['Lower shared learning rate','fine-tuning / 10% shared θₛ LR','单独降低共享层学习率不能可靠保持旧任务，并可能损害新任务适配。','Scene F'],
        ['Parameter preservation','response regularization / parameter-L2','Figure 7 的特定对照中 response regularization 更好。','Scene F'],
        ['Response loss','KD / cross-entropy / L1 / L2','KD 略优，差异不大；不推出所有损失完全相同。','Scene D'],
      ].map(([title,setup,result,scene])=><article key={title}><span>{title}</span><strong>{setup}</strong><p>{result}</p><button type="button" onClick={()=>onNavigate(scene.includes('B')?'B':scene.includes('C')?'C':scene.includes('F')?'F':'D')}>相关机制 · {scene} →</button></article>)}</div></section>

    <section className="v2-i-figure7 v2-state-card"><div className="v2-section-title-row"><div><p className="v2-eyebrow">FIGURE 7 · CLAIM-SPECIFIC READING</p><h2>目标权重、参数约束与 response-loss 选择</h2></div><a href="https://arxiv.org/pdf/1606.09282#page=10" target="_blank" rel="noreferrer">查看 Figure 7 原图 ↗</a></div><div className="v2-i-panels">{[
        ['(a)(b) · λₒ trade-off','Old-task 与 new-task performance 的操作点随 λₒ 改变。','支持稳定—可塑折衷；不构成适用于所有任务的最佳 λ。'],
        ['(a)(b) · parameter-L2','与共享参数软约束 baseline 比较。','在论文测试条件中，response regularization 优于该 baseline。'],
        ['(c)(d) · response losses','KD、cross-entropy、L1 与 L2 的对照。','KD 略优但优势不大；保持旧输出是主要设计主题。'],
        ['(c)(d) · reading boundary','图示性能操作点和具体实验设置。','不从图像像素估读数，不证明任意 loss 完全等价或参数距离无用。'],
      ].map(([title,what,boundary])=><article key={title}><strong>{title}</strong><p>{what}</p><small>{boundary}</small></article>)}</div></section>

    <section className="v2-i-sequential v2-state-card"><div className="v2-section-title-row"><div><p className="v2-eyebrow">FIGURE 4 · SEQUENTIAL EVIDENCE</p><h2>旧任务的 immediate 与 long-term 变化</h2></div><a href="https://arxiv.org/pdf/1606.09282#page=8" target="_blank" rel="noreferrer">查看 Figure 4 原图 ↗</a></div><div className="v2-i-seq-grid"><div><strong>Places365 → VOC parts</strong><span>transport → animals → objects</span><small>VOC 为 multi-label；拆分标签子集，不把共享图像伪装成互斥数据。</small></div><div><strong>ImageNet → Indoor Scenes parts</strong><span>large rooms → medium rooms → small rooms</span><small>序列中按阶段评估各任务表现。</small></div><div><strong>Immediate forgetting</strong><span>加入下一任务前后变化</span><small>一次增量的短窗口。</small></div><div><strong>Long-term forgetting</strong><span>原始阶段对比多阶段后</span><small>跨多个阶段的累计差异；论文没有给出线性累积定律。</small></div></div><p>LwF 在 Figure 4 中通常比 fine-tuning 退化更慢，但多阶段之后旧任务仍可能落后于 Joint Training。精确坐标请读论文原图；此处不描点、不补估值。</p></section>

    <section className="v2-i-graph v2-state-card"><div className="v2-i-graph-heading"><div><p className="v2-eyebrow">EVIDENCE GRAPH · FILTER BY SOURCE TYPE</p><h2>主张与实验之间的证据路径</h2></div><button type="button" className="v2-intro-evidence" onClick={()=>openHub({evidenceId:'E05'})}>Registry ↗</button></div><div className="v2-i-filters">{evidenceKinds.map((kind)=><button type="button" key={kind} aria-pressed={evidenceFilter.includes(kind)} onClick={()=>toggleEvidenceFilter(kind)}>{kind}</button>)}</div><div className="v2-i-graph-nodes">{[
        {id:'Core Claim',kind:'Measured Result' as EvidenceKind,text:'LwF 在报告设置中的表现与边界'},
        {id:'Table 1',kind:'Measured Result' as EvidenceKind,text:'单次新任务对比'},
        {id:'Table 2',kind:'Measured Result' as EvidenceKind,text:'架构 / 训练消融'},
        {id:'Figure 4',kind:'Measured Result' as EvidenceKind,text:'连续任务序列'},
        {id:'Figure 7',kind:'Measured Result' as EvidenceKind,text:'λ、parameter-L2 与 response losses'},
        {id:'C07',kind:'Author Interpretation' as EvidenceKind,text:'新输入响应与旧域行为边界'},
        {id:'Mechanism',kind:'Our Mechanism Explanation' as EvidenceKind,text:'输入覆盖与旧域监督缺口'},
        {id:'Runtime mapping',kind:'Implementation Note' as EvidenceKind,text:'Paper parameter groups → framework objects'},
        {id:'Toy diagnostics',kind:'Teaching Toy' as EvidenceKind,text:'合成梯度与响应曲线仅作机制示意'},
        {id:'General background',kind:'General ML Background' as EvidenceKind,text:'softmax / cross-entropy / backprop 基本事实'},
      ].filter((node)=>evidenceFilter.includes(node.kind)).map((node)=><button type="button" key={node.id} className={selectedNode===node.id?'is-selected':''} onClick={()=>setSelectedNode(node.id)}><span>{node.kind}</span><strong>{node.id}</strong><small>{node.text}</small></button>)}</div><div className="v2-i-graph-detail"><strong>{selectedNode} · 为什么相关？</strong><p>{graphReason(selectedNode)}</p><span>关联路径：{graphLinks(selectedNode)}</span>{selectedNode==='Figure 7'?<button type="button" onClick={()=>openHub({evidenceId:'C11'})}>在 Reference Hub 查看 C11 →</button>:selectedNode==='C07'?<button type="button" onClick={()=>openHub({evidenceId:'C07'})}>查看作者解释 C07 →</button>:null}</div><div className="v2-i-alternatives"><strong>Alternative explanation · Places365 → CUB</strong><span>可能的间接监督覆盖不足</span><i>与</i><span>更一般的共享表示兼容性问题</span><small>论文结果无法单独识别唯一因果原因；两类解释应分别讨论。</small></div></section>

    <section className="v2-i-claims v2-state-card"><div className="v2-section-title-row"><div><p className="v2-eyebrow">CAN I CLAIM THIS? · CLAIM STRENGTH INSPECTOR</p><h2>把一个句子放到证据边界内检查</h2></div></div><label>选择待审主张<select value={judgmentIndex} onChange={(event)=>setJudgmentIndex(Number(event.target.value))}>{judgmentOptions.map((item,index)=><option key={item.text} value={index}>{item.text}</option>)}</select></label><div className="v2-i-judgment"><span className={`is-${judgement.verdict.toLowerCase().replace(/ /g,'-')}`}>{judgement.verdict}</span><blockquote>“{judgement.text}”</blockquote><dl><div><dt>Supporting evidence</dt><dd>{judgement.evidence}</dd></div><div><dt>Boundary</dt><dd>{judgement.boundary}</dd></div><div><dt>Related scenes</dt><dd>{judgement.related}</dd></div></dl></div><div className="v2-i-boundary-map"><div><strong>Tested / discussed</strong><span>视觉分类 · AlexNet · 部分 VGG</span><span>单次与顺序任务加入</span><span>task-specific layers / network expansion</span><span>共享层学习率 / warm-up</span><span>parameter-L2 / response-loss variants</span><span>一项 tracking appendix</span></div><div><strong>Not established as general guarantee</strong><span>no-forgetting theorem</span><span>global function preservation</span><span>arbitrary domain-shift guarantee</span><span>very long task-sequence guarantee</span><span>all modern architectures or continual-learning settings</span><span>future work ≠ demonstrated capability</span></div></div><footer><span>你现在可以把主张、实验条件、证据类型与可推广边界一起读。</span><button type="button" onClick={()=>onNavigate('J')}>进入端到端工作流 Scene J →</button></footer></section>
  </div>;
}

function ClaimChain({claim,onEvidence,onNavigate}:{claim:(typeof claimItems)[number];onEvidence:(id:string)=>void;onNavigate:(scene:'A'|'B'|'C'|'D'|'E'|'F'|'G'|'H'|'J')=>void}) {
  return <div className="v2-i-claim-chain"><div><span>Claim</span><strong>{claim.title}</strong><b className={`is-${claim.verdict.toLowerCase().replace(/ /g,'-')}`}>{claim.verdict}</b></div><i>→</i><div><span>Experimental setup</span><p>{claim.setup}</p></div><i>→</i><div><span>Evidence</span><p>{claim.evidence.join(' · ')}</p><div>{claim.evidence.map((id)=><button key={id} type="button" onClick={()=>onEvidence(id)}>{id} ↗</button>)}</div></div><i>→</i><div><span>Interpretation & boundary</span><p><b>{claim.kind}:</b> {claim.result}</p><p>{claim.interpretation}</p><small>{claim.boundary}</small><div>{claim.related.map((scene)=><button key={scene} type="button" onClick={()=>onNavigate(scene as 'A'|'B'|'C'|'D'|'E'|'F'|'G'|'H'|'J')}>Scene {scene} →</button>)}</div></div></div>;
}
function ExperimentSetup(){const old=datasetById.get('dataset:imagenet')!;const next=datasetById.get('dataset:cub')!;return <div className="v2-i-setup"><div><span>Old task</span><strong>{old.title} · {old.classes}</strong></div><div><span>New task</span><strong>{next.title} · {next.classes}</strong></div><div><span>Architecture / task-specific layer</span><strong>{table1ImageNetCub.experiment.architecture}</strong></div><div><span>Data split · metric · runs</span><strong>{table1ImageNetCub.experiment.split} · {table1ImageNetCub.experiment.metric} · {table1ImageNetCub.experiment.runs}</strong></div><small>Training data access depends on method: Joint Training uses old training data and labels; LwF does not.</small></div>;}
function PerformancePlot({onSelect,selected}:{onSelect:(id:Table1MethodId)=>void;selected:Table1MethodId}){const x=(value:number)=>46+(value-49)/9*280;const y=(value:number)=>214-(value-49)/10*182;return <div className="v2-i-plot"><strong>Old × New performance · clickable methods</strong><svg viewBox="0 0 360 260" role="img" aria-label="ImageNet validation accuracy 对 CUB test accuracy 的 LwF 方法比较。坐标使用 Table 1(a) 的旧、新任务准确率"><path d="M46 26 V214 H326" fill="none" stroke="#c9c7c1"/><text x="180" y="250" textAnchor="middle">Old-task accuracy (%)</text><text x="14" y="120" transform="rotate(-90 14 120)" textAnchor="middle">New-task accuracy (%)</text>{table1ImageNetCub.methods.map((method,index)=>{const point=table1Absolute(method);return <g key={method.id} onClick={()=>onSelect(method.id)} role="button" tabIndex={0} aria-label={`${method.label}: old ${point.old.toFixed(1)}%, new ${point.next.toFixed(1)}%`} onKeyDown={(event)=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();onSelect(method.id);}}} style={{cursor:'pointer'}}><circle cx={x(point.old)} cy={y(point.next)} r={method.id===selected?7:5.5} fill={['#536a9e','#bd6b62','#4c8a78','#9b7d4f'][index]} stroke={method.id===selected?'#252d40':'#fff'} strokeWidth={method.id===selected?2:1.4}/><text x={x(point.old)+7} y={y(point.next)-7} className="plot-label">{method.label}</text></g>;})}</svg><small>坐标来自 Table 1(a) 的重构绝对值；图仅供逐点检查，不自动评选 winner。</small></div>;}
function MethodConstraint({method,info,absolute}:{method:Table1Row;info:string;absolute:{old:number;next:number}}){return <article className="v2-i-method-detail"><span>Selected method · {method.label}</span><strong>{absolute.old.toFixed(1)}% old · {absolute.next.toFixed(1)}% new</strong><p>{info}</p><dl><div><dt>Old data / labels during training</dt><dd>{method.oldData?'Yes · old data and labels available':'No old training data'}</dd></div><div><dt>Shared θₛ</dt><dd>{method.trainableShared?'Trainable':'Frozen'}</dd></div><div><dt>Old-response constraint</dt><dd>{method.oldResponse?'Teacher(Xₙ) response matching':'None'}</dd></div><div><dt>Value provenance</dt><dd>{method.id==='lwf'?'Printed absolute baseline':'reconstructed from paper-reported delta'}</dd></div></dl></article>;}
function methodCardId(id:Table1MethodId){return id==='lwf'?'method:lwf':id==='fine-tuning'?'method:fine_tuning':id==='feature-extraction'?'method:feature_extraction':'method:joint_training';}
function signed(value:number){return `${value>0?'+':''}${value.toFixed(1)}`;}
function graphReason(id:string){const reasons:Record<string,string>={'Core Claim':'主张需要同时检查单次任务性能、序列表现、信息条件与适用边界。','Table 1':'Table 1 提供 old/new task 的实测指标；部分方法行是相对 LwF 的带符号差值。','Table 2':'Table 2 将训练设置与结构消融关联到是否需要特定实现选择。','Figure 4':'Figure 4 记录连续任务加入后的表现，支持讨论局部保持与序列退化。','Figure 7':'Figure 7 对应 λ 折衷、parameter-L2 对照及 response-loss 变体。','C07':'C07 是作者对新输入响应和旧任务行为覆盖边界的解释，不是量化域距离。','Mechanism':'本页以覆盖缺口解释为什么 Xₙ 上的匹配不能推出 pₒ 上全局保持；属于机制解释。'};return reasons[id]||reasons['Core Claim'];}
function graphLinks(id:string){const links:Record<string,string>={'Core Claim':'Table 1 · Table 2 · Figure 4 · Figure 7','Table 1':'C06 · E01–E05 · Scene A / G','Table 2':'A08 · C05 · Scene B / C','Figure 4':'E05 · Scene H','Figure 7':'C04 · C08 · C11 · Scene D / E / F','C07':'Scene F / G / H','Mechanism':'Scene G / H'};return links[id]||links['Core Claim'];}
function registryEvidenceId(id:string){const canonical:Record<string,string>={'Table 1':'E01','Table 2':'A08','Figure 4':'E05','Figure 7(a)(b)':'C11','Figure 7(c)(d)':'C08'};return canonical[id]||id;}
